springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

spring:
  messages:
    always-use-message-format: true
    basename: i18n.messages
    cache-duration: 5000s
    encoding: UTF-8
    fallback-to-system-locale: true
  datasource:
    url: jdbc:h2:mem:livedb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
